Adjust startup files

diff --git a/build-armbian/common-files/files/usr/sbin/armbian-install b/build-armbian/common-files/files/usr/sbin/armbian-install
--- a/build-armbian/common-files/files/usr/sbin/armbian-install
+++ b/build-armbian/common-files/files/usr/sbin/armbian-install
@@ -145,12 +145,20 @@ printf "%-s\n" "----------------------------------------------------------------
 
 read -p "Please Input ID: " boxtype
 if [ "${boxtype}" -eq "0" ]; then
+    read -p "Please Input SoC Name: " AMLOGIC_SOC
+    AMLOGIC_SOC="${AMLOGIC_SOC}"
+    #
     read -p "Please Input DTB Name: " FDTFILE
-    FDTFILE=${FDTFILE}
-    AMLOGIC_SOC=""
-    UBOOT_OVERLOAD=""
-    MAINLINE_UBOOT=""
-    ANDROID_UBOOT=""
+    FDTFILE="${FDTFILE}"
+    #
+    read -p "Please Input UBOOT_OVERLOAD Name: " UBOOT_OVERLOAD
+    UBOOT_OVERLOAD="${UBOOT_OVERLOAD}"
+    #
+    read -p "Please Input MAINLINE_UBOOT Name: " MAINLINE_UBOOT
+    MAINLINE_UBOOT="${MAINLINE_UBOOT}"
+    #
+    read -p "Please Input ANDROID_UBOOT Name: " ANDROID_UBOOT
+    ANDROID_UBOOT="${ANDROID_UBOOT}"
 else
     ret=$(search_aml_model "${boxtype}")
     if [ "${ret}" == "" ]; then
@@ -158,22 +166,22 @@ else
         exit 1
     fi
 
-    AMLOGIC_SOC=$(echo "${ret}" | awk -F ':' '{print $3}')
-    FDTFILE=$(echo "${ret}" | awk -F ':' '{print $4}')
-    UBOOT_OVERLOAD=$(echo "${ret}" | awk -F ':' '{print $5}')
-    MAINLINE_UBOOT=$(echo "${ret}" | awk -F ':' '{print $6}')
-    ANDROID_UBOOT=$(echo "${ret}" | awk -F ':' '{print $7}')
+    AMLOGIC_SOC="$(echo "${ret}" | awk -F ':' '{print $3}')"
+    FDTFILE="$(echo "${ret}" | awk -F ':' '{print $4}')"
+    UBOOT_OVERLOAD="$(echo "${ret}" | awk -F ':' '{print $5}')"
+    MAINLINE_UBOOT="$(echo "${ret}" | awk -F ':' '{print $6}')"
+    ANDROID_UBOOT="$(echo "${ret}" | awk -F ':' '{print $7}')"
 fi
 # Set model list, end ------------
 
-echo -e "Input ID: [ ${boxtype} ]"
-echo -e "FDTFILE: [ ${FDTFILE} ]"
-echo -e "UBOOT_OVERLOAD: [ ${UBOOT_OVERLOAD} ]"
+echo "Input ID: [ ${boxtype} ]"
+echo "FDTFILE: [ ${FDTFILE} ]"
+echo "UBOOT_OVERLOAD: [ ${UBOOT_OVERLOAD} ]"
 
 # Check if u-boot version 5.10 or later exists
-if [ "${K510}" -eq "1" ]; then
-    [[ -z "${UBOOT_OVERLOAD}" || ! -f "/boot/${UBOOT_OVERLOAD}" ]] && echo "Have no the 5.10 kernel u-boot file." && exit 1
-fi
+#if [ "${K510}" -eq "1" ]; then
+[[ -z "${FDTFILE}" || -z "${UBOOT_OVERLOAD}" || ! -f "/boot/${UBOOT_OVERLOAD}" ]] && echo "The DTB or UBOOT_OVERLOAD is invalid, stop the install." && exit 1
+#fi
 
 systemctl stop armbian-resize-filesystem.service
 systemctl disable armbian-resize-filesystem.service
@@ -266,25 +274,21 @@ cp -rf /boot/* ${DIR_INSTALL} && sync
 rm -rf ${DIR_INSTALL}/'System Volume Information' 2>/dev/null
 
 # Edit the uEnv.txt (s912-t95z-plus is /boot/extlinux/extlinux.conf)
-#if [[ "${FDTFILE}" == "meson-gxm-t95z-plus.dtb" ]]; then
-boot_conf_file="extlinux/extlinux.conf"
-#else
-#    boot_conf_file="uEnv.txt"
-#fi
-echo -e "The boot file is [ ${boot_conf_file} ]"
-#
-#Get the current UUID, such as [ UUID=dc20e16b-1234-5678-a636-7945a906d0c6 ]
-CURRENT_ROOTFS_UUID="$(cat ${DIR_INSTALL}/${boot_conf_file} 2>/dev/null | grep -oE "append.*" | sed -e 's/^.*root=//' -e 's/ .*$//')"
-[ -z "${CURRENT_ROOTFS_UUID}" ] && echo "The current UUID is invalid, cannot continue." && exit 1
-echo "CURRENT_ROOTFS_UUID: ${CURRENT_ROOTFS_UUID}"
-#
-if [[ -f "${DIR_INSTALL}/${boot_conf_file}" ]]; then
-    sed -i "s|${CURRENT_ROOTFS_UUID}|UUID=${ROOTFS_UUID}|g" ${DIR_INSTALL}/${boot_conf_file}
-    sed -i "s|meson.*.dtb|${FDTFILE}|g" ${DIR_INSTALL}/${boot_conf_file}
+if [[ "${FDTFILE}" == *t95z* ]]; then
+    boot_conf_file="extlinux/extlinux.conf"
 else
-    echo "The boot file [ ${boot_conf_file} ] does not exist."
-    exit 1
+    boot_conf_file="uEnv.txt"
 fi
+echo "The boot file is [ ${boot_conf_file} ]"
+[[ ! -f "${DIR_INSTALL}/${boot_conf_file}" ]] && echo "The boot file [ ${boot_conf_file} ] does not exist." && exit 1
+#
+#Get the current UUID, such as [ dc20e16b-1234-5678-a636-7945a906d0c6 ]
+CURRENT_ROOTFS_UUID="$(cat ${DIR_INSTALL}/${boot_conf_file} 2>/dev/null | grep -oE "root=UUID.*" | sed -e 's/^.*root=UUID=//' -e 's/ .*$//')"
+[ -z "${CURRENT_ROOTFS_UUID}" ] && echo "The current UUID is invalid, cannot continue." && exit 1
+echo "CURRENT_ROOTFS_UUID: [ ${CURRENT_ROOTFS_UUID} ]"
+#
+sed -i "s|${CURRENT_ROOTFS_UUID}|${ROOTFS_UUID}|g" ${DIR_INSTALL}/${boot_conf_file}
+sed -i "s|meson.*.dtb|${FDTFILE}|g" ${DIR_INSTALL}/${boot_conf_file}
 
 rm ${DIR_INSTALL}/s9*
 rm ${DIR_INSTALL}/aml*
@@ -305,7 +309,7 @@ if [ "${K510}" -eq "1" ]; then
         chmod +x ${DIR_INSTALL}/u-boot.ext
         chmod +x ${DIR_INSTALL}/u-boot.emmc
     else
-        echo "Have no the 5.10 kernel u-boot file."
+        echo "Have no the u-boot file."
         exit 1
     fi
 fi
