armbian-tf: use btrfs format

diff --git a/build-armbian/common-files/files/usr/sbin/armbian-tf b/build-armbian/common-files/files/usr/sbin/armbian-tf
--- a/build-armbian/common-files/files/usr/sbin/armbian-tf
+++ b/build-armbian/common-files/files/usr/sbin/armbian-tf
@@ -58,6 +58,12 @@ esac
 create_new_part() {
     echo -e "${STEPS} Start creating a new partition ... "
 
+    # generate uuid
+    ROOTFS_UUID="$(cat /proc/sys/kernel/random/uuid)"
+    [ -z "${ROOTFS_UUID}" ] && ROOTFS_UUID="$(uuidgen)"
+    [ -z "${ROOTFS_UUID}" ] && echo "The uuidgen is invalid, cannot continue." && exit 1
+    echo "ROOTFS_UUID: ${ROOTFS_UUID}"
+
     # Get the starting position of the p3 partition
     START_P3=$(fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | echo $(($(xargs) + 1)))
     if [[ -z "${START_P3}" || -z "$(echo ${START_P3} | sed -n "/^[0-9]\+$/p")" ]]; then
@@ -91,9 +97,9 @@ EOF
 
     echo -e "${STEPS} Create shared filesystem ... "
     mkdir -p /mnt/${PT_PRE}3 && sync
-    mkfs.ext4 -F -p -L "${LB_PRE}SHARED" "/dev/${PT_PRE}3"
-    mount -t ext4 "/dev/${PT_PRE}3" "/mnt/${PT_PRE}3"
-    echo "/dev/${PT_PRE}3 /mnt/${PT_PRE}3 ext4 defaults 0 0" >>/etc/fstab
+    mkfs.btrfs -f -U ${ROOTFS_UUID} -L "${LB_PRE}SHARED" -m single "/dev/${PT_PRE}3"
+    mount -t btrfs -o compress=zstd:6 "/dev/${PT_PRE}3" "/mnt/${PT_PRE}3"
+    echo "UUID=${ROOTFS_UUID}  /mnt/${PT_PRE}3  btrfs  compress-force=zstd:6  0 0" >>/etc/fstab
     sync
 
     echo -e "${INFO} The new partition information: \n$(df -hT /dev/${PT_PRE}3)"
@@ -116,6 +122,7 @@ expand_current_part() {
 
     echo -e "${STEPS} Expansion file system ... "
     resize2fs /dev/${ROOT_PTNAME}
+    btrfs filesystem resize max /
 
     echo -e "${INFO} Current partition information: \n$(df -hT /)"
     echo -e "${SUCCESS} The current partition expansion is successful."
